ALTER TABLE goals
    ADD COLUMN IF NOT EXISTS hours_per_week INT NOT NULL DEFAULT 1;

ALTER TABLE goals
    ADD COLUMN IF NOT EXISTS progress INT NOT NULL DEFAULT 0;

ALTER TABLE goals
    ALTER COLUMN status SET DEFAULT 'planning';

ALTER TABLE phases
    ADD COLUMN IF NOT EXISTS progress INT NOT NULL DEFAULT 0;

ALTER TABLE phases
    ADD COLUMN IF NOT EXISTS "order" INT NOT NULL DEFAULT 1;

ALTER TABLE phases
    ALTER COLUMN status SET DEFAULT 'not_started';

ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE tasks
ALTER COLUMN estimated_time TYPE INT;

ALTER TABLE tasks
    ALTER COLUMN status SET DEFAULT 'todo';
