version: "3.8"
services:
  db:
    image: postgres:17-alpine
    container_name: auth_service_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_service
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: